---
title: "Visualizations"
author: "Dayana Meza"
date: "4/19/2021"
output: html_document
---

```{r, include=FALSE}
# Load all packages here
library(ggplot2)
library(lubridate)
library(knitr)
library(tidytext)
library(dplyr)
library(stringr)
library(rpart.plot)
library(tidymodels)
library(text2vec)
library(ggrepel)

data(stop_words)

# Load the data 
#amenities <- read.csv("amenities.csv", stringsAsFactors = FALSE)
sale <- read.csv("sale_listings.csv", stringsAsFactors = FALSE)

```

```{r}
# Datasets 
data <- sale %>% 
  
#Uncomment to merge amenities and sale 
  #merge(sale,amenities,by="property_id") %>% 
  
  # select only descriptions for now
  select(listing_description,price,property_id,bedrooms, bathrooms) 
  
```

```{r}
# Cleaning the Data: Removing Stop Words, Stemming
data <- data %>%
  unnest_tokens(word, listing_description) %>% 
  
  # Remove Stop Words (e.g., "the")
  anti_join(stop_words) %>% 
  
  # Stemming 
  mutate(stem = wordStem(word)) %>% 
  
      # add word count for each stem 
  add_count(stem) %>% 
  
    # Comment out because it interferes with word embedding
  #group_by(word) %>% 
  #mutate(count = n()) %>% 
  #arrange(desc(count)) %>% 
  
      #then, let’s filter out words that are used only rarely in this dataset 

  filter(n >= 50) %>%
  select(-n)
```

<!-- Frequency --> 
  <!-- Words -->
```{r}
freq_word <- data %>% 
    group_by(word) %>% 
  mutate(count = n(), 
         avg_price = mean(price),
         avg_bed = mean(bedrooms),
         avg_bath = mean(bathrooms)
         ) %>% 
  arrange(desc(count)) %>% 
  select(count, avg_price,word,avg_bed,avg_bath)
```

```{r}
freq_word_duplicated <- freq_word[!duplicated(freq_word), ]
```

```{r}
# Top 40 Words
freq5_word_duplicated <- freq_word_duplicated %>% 
  head(40)
```

```{r}
# Bottom 40 Words
freq5_word_duplicated_bottom <- freq_word_duplicated %>% 
  tail(40)
```

   <!-- Stem -->
```{r}
freq_stem <- data %>% 
    group_by(stem) %>% 
  mutate(count = n(), 
         avg_price = mean(price),
         avg_bed = mean(bedrooms),
         avg_bath = mean(bathrooms)
         ) %>% 
  arrange(desc(count)) %>% 
  select(count, avg_price,stem,avg_bed,avg_bath)
```

```{r}
freq_stem_duplicated <- freq_stem[!duplicated(freq_stem), ]
```

```{r}
# Top 40 Stems
freq5_stem_duplicated <- freq_stem_duplicated %>% 
  head(40)
```

<!-- Top -->
```{r}
# Bottom 40 Stems
freq5_stem_duplicated_bottom <- freq_stem_duplicated %>% 
  tail(40)
```
<!--- Data Visualizations -->

  <!-- TOP --> 
  
```{r, width = 100, height = 100}
# Top Words
ggplot(data = freq5_word_duplicated, mapping = aes(x = count, y = avg_price, color = avg_bath, size = avg_bed, )) + 
  geom_jitter(width = 50, height = 50) +
  geom_label_repel(aes(label = word), size = 3) + labs(title = "Top 40 Frequent Words vs. Average Price", subtitles = "By average number of bedrooms & bathrooms", x = "Frequency of Word", y = "Average Price", color = "Average # of Bathroom", size = "Average # of Bedrooms") + theme(legend.position = "bottom", plot.background = element_rect(
    fill = "white",
    colour = "black",
    size = 1), axis.text.y = element_text(color="#000000"),axis.text.x = element_text(color="#000000")) + scale_y_continuous(labels=scales::dollar_format()) 

```
  
```{r, width = 100, height = 100}
# Top Stems
ggplot(data = freq5_stem_duplicated, mapping = aes(x = count, y = avg_price, color = avg_bath, size = avg_bed, )) + 
  geom_jitter(width = 50, height = 50) +
  geom_label_repel(aes(label = stem), size = 3) + labs(title = "Top 40 Frequent Stems vs. Average Price", subtitles = "By average number of bedrooms & bathrooms", x = "Frequency of Stem", y = "Average Price", color = "Average # of Bathroom", size = "Average # of Bedrooms") + theme(plot.background = element_rect(
    fill = "white",
    colour = "black",
    size = 1), axis.text.y = element_text(color="#000000"),axis.text.x = element_text(color="#000000")) + scale_y_continuous(labels=scales::dollar_format())
```


