---
title: "decision_tree_analysis"
output: html_document
---

```{r loading packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(rattle)
library(rpart)
library(randomForest)
library(MLmetrics)
library(textdata)
library(tidytext)
library(SnowballC)
```

```{r message=FALSE, warning=FALSE}
#use imputed data for linear model 
source("pre-processing.R")
load_data() # creates two dataframes in the global environment

clean_data() # cleans the data

sale_listings_imputed <- impute_data() # imputes size values and returns a new dataframe

#call data with all text-based variables 
source("text_processing.R")

text_var()
```

```{r adding new variables to improve baseline model}
set.seed(410)
train <- sale_listings_ss %>% sample_frac(.70)
test <- sale_listings_ss %>% anti_join(train)

numFolds <- trainControl(method = "cv", number = 5)

set.seed(410)
caret_rf_1 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft , 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_1 <- test %>%
  mutate(price_hat_1 = predict(caret_rf_1, test))

MAPE(y_pred = test_caret_rf_1$price_hat_1, y_true = test$price)
RMSE(test_caret_rf_1$price_hat_1, test$price)
RMSLE(test_caret_rf_1$price_hat_1, test$price)


set.seed(410)
caret_rf_2 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft +
                          unittype , 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_2 <- test %>%
  mutate(price_hat_2 = predict(caret_rf_2, test))

MAPE(y_pred = test_caret_rf_2$price_hat_2, y_true = test$price)
RMSE(test_caret_rf_2$price_hat_2, test$price)
RMSLE(test_caret_rf_2$price_hat_2, test$price)


set.seed(410)
caret_rf_3 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft +
                          unittype +
                            county, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_3 <- test %>%
  mutate(price_hat_3 = predict(caret_rf_3, test))

MAPE(y_pred = test_caret_rf_3$price_hat_3, y_true = test$price)
RMSE(test_caret_rf_3$price_hat_3, test$price)
RMSLE(test_caret_rf_3$price_hat_3, test$price)


set.seed(410)
caret_rf_4 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft +
                          unittype +
                            county +
                            is_historic, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_4 <- test %>%
  mutate(price_hat_4 = predict(caret_rf_4, test))

MAPE(y_pred = test_caret_rf_4$price_hat_4, y_true = test$price)
RMSE(test_caret_rf_4$price_hat_4, test$price)
RMSLE(test_caret_rf_4$price_hat_4, test$price)

set.seed(410)
caret_rf_5 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft +
                          unittype +
                            county +
                            is_historic +
                            floor_count, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_5 <- test %>%
  mutate(price_hat_5 = predict(caret_rf_5, test))

MAPE(y_pred = test_caret_rf_5$price_hat_5, y_true = test$price)
RMSE(test_caret_rf_5$price_hat_5, test$price)
RMSLE(test_caret_rf_5$price_hat_5, test$price)

set.seed(410)
caret_rf_6 <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft +
                           unittype +
                            county +
                            is_historic +
                            floor_count +
                            city_group, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf_6 <- test %>%
  mutate(price_hat_6 = predict(caret_rf_6, test))

MAPE(y_pred = test_caret_rf_6$price_hat_6, y_true = test$price)
RMSE(test_caret_rf_6$price_hat_6, test$price)
RMSLE(test_caret_rf_6$price_hat_6, test$price)


set.seed(410)
caret_rf <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft + 
                           unittype + 
                           county + 
                           is_historic + 
                           floor_count + 
                           city_group + 
                           stainless_steel + hw_floors + wd + pet_friendly, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

test_caret_rf <- test %>%
  mutate(price_hat = predict(caret_rf, test))

MAPE(y_pred = test_caret_rf$price_hat, y_true = test$price)
RMSE(test_caret_rf$price_hat, test$price)
RMSLE(test_caret_rf$price_hat, test$price)

# bed
# bath
# size_sqft
# MAPE 0.6001674
# RMSE 662274.4
# RMSLE 0.5694857

# unittype
# MAPE 0.515053
# RMSE 585639.2
# RMSLE 0.5112604

# county 
# MAPE 0.3378906
# RMSE 456559.4
# RMSLE 0.3792182

# is_historic
# MAPE 0.3289417
# RMSE 444032.5
# RMSLE 0.3719362

# floor_count
# MAPE  0.2972872
# RMSE 410053.5
# RMSLE 0.3484736

# city_group 
# MAPE 0.2705793
# RMSE 400027.5
# RMSLE 0.3262318

# stainless_steel 
# hw_floors 
# wd 
# pet_friendly
# MAPE 0.2656724
# RMSE 396093.3
# RMSLE 0.3228432

```

```{r adding sentiment scores to model}
#about 2000 listings does not have a score -- mainly bc their description does not contain any words associated with sentiments; will assign 0 
numFolds <- trainControl(method = "cv", number = 5)
set.seed(410)
caret_rf_score <- caret::train(price ~ bedrooms + 
                           bathrooms + 
                           size_sqft + 
                           unittype + 
                           county + 
                           is_historic + 
                           floor_count + 
                           city_group + 
                           stainless_steel + hw_floors + wd + pet_friendly +
                             score, 
                          data = train, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)


test_rf_score <- test %>%
  mutate(price_hat_score = predict(caret_rf_score, test))

MAPE(y_pred = test_rf_score$price_hat_score, y_true = test$price)
RMSE(test_rf_score$price_hat_score, test$price)
RMSLE(test_rf_score$price_hat_score, test$price)

# sentiment score
# MAPE 0.2603957
# RMSE 390974
# RMSLE  0.3181844
#I tried logprice and logsize but the RMSE for the same model went worse; probably we just go with raw price 
rf_score_imp <- varImp(caret_rf_score)
varimp_score <- varImp(caret_rf_score)$importance %>%
  arrange(desc(Overall))
varimp_score <- as_tibble(varimp_score, rownames = "variable")
plot(rf_score_imp)

```


# model tuning 
```{r}
library(caret)
#select all variables in the model for model tuning - let decision tree decide which one is important to keep
#in total we have 39 variables; if taken all levels of categorical vars into account, we have 71 variables 
sale_listings_tune <- sale_listings_ss %>%
  select(-id, -property_id, -listing_description, -size_sqft_na, -addr_street, -addr_unit, -zipcode, -year_built, -lat, -long, -major_city)
head(sale_listings_tune)

set.seed(410)
traint <- sale_listings_tune %>% sample_frac(.70)
testt <- sale_listings_tune %>% anti_join(traint)

#random forest 
#the default mtry for regression is var/3, the grid is set up around that range
#this take forever to run - the best model is mtry = 26 

numFolds <- trainControl(method = "cv", number = 5)
mtry <- 20:35
tunegrid <- expand.grid(.mtry = mtry)
set.seed(410)
best_rf <- caret::train(price ~ ., 
                          data = traint, 
                          method = "rf",
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          tuneGrid = tunegrid,
                          na.action = na.omit)


#extract the best mtry from the best_fr model 
best_mtry <- best_rf$bestTune$mtry 
varImp(best_rf)

best_mtry <- 32
bestmtry <- expand.grid(.mtry = best_mtry)

set.seed(410)
#run the following model for mtry = 32
#RMSE for train: 376945.7
mtry_32 <- caret::train(price ~ ., 
                          data = traint, 
                          method = "rf",
                          tuneGrid = bestmtry,
                          ntree = 100, 
                          trControl = numFolds,
                          metric = "RMSE",
                          na.action = na.omit)

varimp_m32 <- varImp(mtry_32)
plot(varimp_m32, top = 50)

test_rf32 <- testt %>%
  mutate(price_hat = predict(mtry_32, testt))

MAPE(y_pred = test_rf32$price_hat, y_true = testt$price)
RMSE(test_rf32$price_hat, testt$price)
RMSLE(test_rf32$price_hat, testt$price)
#mape 0.2484644
#rmse 381930.2
#rmlse 0.3063396
colnames(sale_listings_tune)
```
# Mtry result tab
```{r}
result_tab <- best_rf[["results"]]
psychTools::df2latex(result_tab, digits = 3, short.names = FALSE, )
```

# Comparison of models 
```{r}
rf_metrics <- data.frame(Variables = c("bed, bath, 
                                       size_sqft",
                             "unittype",
                             "county",
                             "is_historic",
                             "floor_count",
                             "city_group",
                             "stainless_steel, 
                             hw_floors, wd, pet",
                             "sentiment_score",
                             "all variables"),
                    MAPE = c(0.600,
                             0.515,
                             0.338,
                             0.329,
                             0.297,
                             0.270,
                             0.266,
                             0.260,
                             0.248
                             ),
                    RMSE = c(662274.4,
                             585639.2,
                             456559.4,
                             444032.5,
                             410053.5,
                             400027.5,
                             396093.3,
                             390974,
                             381930.2
                             ),
                    RMSLE = c(0.569,
                              0.511,
                              0.379,
                              0.372,
                              0.348,
                              0.326,
                              0.322,
                              0.318,
                              0.306
                    ))
```

```{r metrics plot}
rf_mape_plot <- rf_metrics %>%
ggplot(aes(y = MAPE, x = fct_reorder(Variables, MAPE, .desc = TRUE))) + 
  geom_line(group=1, color="#000066") +
  scale_y_continuous(labels = scales::percent, limits = c(0.2,0.7)) +
  labs(x="Variables", title = "MAPE across Random Forest Models") + 
  geom_text(aes(label=MAPE), vjust=-1, size=3, color="#000066") +
 theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

rf_rmse_plot <- rf_metrics %>%
ggplot(aes(y = RMSE, x = fct_reorder(Variables, RMSE, .desc = TRUE))) + 
  geom_line(group=1, color="#000066") +
  scale_y_continuous(labels = scales::comma, limits = c(350000, 700000)) +
  labs(x="Variables", title = "RMSE across Random Forest Models") + 
  geom_text(aes(label=RMSE), vjust=-1, size=3, color="#000066") +
 theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

rf_rmsle_plot <- rf_metrics %>%
ggplot(aes(y = RMSLE, x = fct_reorder(Variables, RMSLE, .desc = TRUE))) + 
  geom_line(group=1, color="#000066") +
  scale_y_continuous(limits = c(0.3, 0.6)) +
  labs(x="Variables", title = "RMSLE across Random Forest Models") + 
  geom_text(aes(label=RMSLE), vjust=-1, size=3, color="#000066") +
 theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

rf_mape_plot
  rf_rmse_plot
  rf_rmsle_plot

```


https://rstudio-pubs-static.s3.amazonaws.com/71575_4068e2e6dc3d46a785ad7886426c37db.html

https://topepo.github.io/caret/available-models.html
