---
title: "random_forest_0420"
author: Elaine Ye 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(tidymodels)
library(leaps)
library(MLmetrics)
library(caret)
library(randomForest)
```

```{r message=FALSE, warning=FALSE}
#use imputed data for linear model 
source("pre-processing.R")
load_data() # creates two dataframes in the global environment

clean_data() # cleans the data

sale_listings_imputed <- impute_data() # imputes size values and returns a new dataframe
```

### More data cleaning from Yanwan on unittype and cities 
```{r}
sale_listings_imputed <- sale_listings_imputed %>%
    mutate(unit_group = ifelse(unittype %in% c("B", "M", "Z"), 1, 
                                ifelse(unittype %in% c("H", "T"), 2, 
                                       ifelse(unittype %in% c("A", "C", "R", "P", "Y"), 3, 
                                              ifelse(unittype %in% c("D", "F", "N"), 4,
                                                     ifelse(unittype %in% c("X", "U", "?"), 5, unittype)))))) %>%
    mutate(unit_group = as.factor(unit_group))
  
sale_listings_imputed <- sale_listings_imputed %>%
    mutate(city_group = ifelse(major_city == "Long Island City", 1, 
                               ifelse(major_city == "New York", 2, 
                                      ifelse(major_city %in% c("Astoria", "Brooklyn",
                                                               "Hoboken", "Toms River",
                                                               "Flushing", "Edgewater",
                                                               "Elmhurst", "Sunnyside"), 3,
                                             4)))) %>%
    mutate(city_group = as.factor(city_group))

sale_listings_imputed <- sale_listings_imputed %>%
  mutate(is_historic = ifelse(is.na(is_historic) == TRUE, "0", is_historic))

sale_listings_ss <- sale_listings_imputed %>%
  mutate(listing_description = ifelse(is.na(listing_description) == TRUE, 0, listing_description)) %>%
  mutate(
    stainless_steel = as.integer(str_detect(listing_description, "[Ss]tainless.[Ss]teel")),
    hw_floors = as.integer(str_detect(listing_description, "[Hh]ardwood.[Ff]loors?")),
    wd = as.integer(str_detect(listing_description, c(
      "[Ww]d",
      "[Ww]/d",
      "[Ww]&d",
      "[Ww] & d",
      "[Ww]asher/dryer",
      "[Ww]asher / dryer",
      "[Ww]asher and dryer",
      "[Ww]asher&dryer",
      "[Ww]asher & dryer",
      "[Ww]asher-dryer",
      "[Ww]asher dryer"
    ))),
    steel_app = as.integer(str_detect(listing_description, "[Ss]teel.[Aa]ppliances?")),
    fitness = as.integer(str_detect(listing_description, c(
      "[Ff]itness",
      "[Ff]itness center",
      "[Ff]itness-center"
    ))),
    renovate = as.integer(str_detect(listing_description, "[Rr]enovat*")),
    closet_space = as.integer(str_detect(listing_description, "[Cc]loset.[Ss]pace")),
    spacious = as.integer(str_detect(listing_description, "[Ss]pacious*")),
    storage = as.integer(str_detect(listing_description, "[Ss]torage")),
    closet_space = as.integer(str_detect(listing_description, "[Cc]loset.[Ss]pace")),
    roof_deck = as.integer(str_detect(listing_description, "[Rr]oof.[Dd]eck")),
    park = as.integer(str_detect(listing_description, "[Pp]ark")),
    balcony = as.integer(str_detect(listing_description, "[Bb]alcony")),
    courtyard = as.integer(str_detect(listing_description, "[Cc]ourtyard")),
    view = as.integer(str_detect(listing_description, "[Vv]iew*")),
    window = as.integer(str_detect(listing_description, "[Ww]indow*")),
    natural_light = as.integer(str_detect(listing_description, "[Nn]atural.[Ll]ight")),
    en_suite = as.integer(str_detect(listing_description, "[Ee]n.[Ss]uite")),
    pet_friendly = as.integer(str_detect(listing_description, "[Pp]et.[Ff]riendly")),
    tree_lined = as.integer(str_detect(listing_description, "[Tt]ree.[Ll]ined")),
    central_park = as.integer(str_detect(listing_description, "[Cc]entral.[Pp]ark")),
    outdoor_space = as.integer(ifelse((park | balcony | courtyard | roof_deck | central_park | tree_lined) == 1, 1, 0))                              
  )


```

```{r split data to train and test}
#error: cannot change value of locked binding for 'train'
#ml_setup(sale_listings_imputed) 

train <- sale_listings_ss%>% sample_frac(.70)
test <- sale_listings_ss %>% anti_join(train)

#+1, -1 are supposed to optimize rmlse
train <- train %>%
  mutate(log10price = log10(price + 1)) %>%
  mutate(log10size = log10(size_sqft))

test <- test %>%
  mutate(log10size = log10(size_sqft))


```


## Model setup 

```{r}
#no text features 
#year_built has lots of NA 
model_formula <-
  "log10price ~ bedrooms + 
                bathrooms + 
                log10size + 
                floor_count + 
                is_historic + 
                state + 
                unit_group + 
                city_group " %>%
  as.formula()
```

```{r}
#with some text features 
#year_built has lots of NA 
model_formula_txt <-
  "log10price ~ bedrooms + 
                bathrooms + 
                log10size + 
                floor_count + 
                is_historic + 
                state + 
                unit_group + 
                city_group +
                stainless_steel +
                hw_floors +
                renovate + 
                outdoor_space + 
                central_park" %>%
  as.formula()
```

```{r}
fit_control <- trainControl(method = "cv", number = 5)

# Setup search grid of "tuning" parameters
# 2:8
mtry <- 2
tunegrid <- expand.grid(.mtry = mtry)
```


## Model fitting
```{r}
#no text features 
#how to cross validate randomForest??? 
model_rf <- randomForest(
  # Model formula
  form = model_formula,
  # Training data
  data = train, 
  # At each node of tree, number of features/predictor variables to randomly
  # choose from for splitting:
  mtry = 2,
  # Number of bagged (bootstrap aggregated) trees in your forest:
  ntree = 100 
)

#use caret
model_rf_caret <- caret::train(
  # Model formula
  form = model_formula,
  # Training data
  data = train, 
  # Set method to randomForests. Note: this is where you can switch out to
  # different methods
  method = "rf",
  # Score/error metric used:
  metric = "RMSE",
  # Cross-validation settings:
  trControl = fit_control,
  # Search grid of tuning parameters
  tuneGrid = tunegrid,
  na.action = na.pass
  )

```

```{r}
#with text features 
#how to cross validate randomForest??? 
model_rf_txt <- randomForest(
  # Model formula
  form = model_formula_txt,
  # Training data
  data = train, 
  # At each node of tree, number of features/predictor variables to randomly
  # choose from for splitting:
  mtry = 2,
  # Number of bagged (bootstrap aggregated) trees in your forest:
  ntree = 100 
)

#use caret
model_rf_caret_txt <- caret::train(
  # Model formula
  form = model_formula_txt,
  # Training data
  data = train, 
  # Set method to randomForests. Note: this is where you can switch out to
  # different methods
  method = "rf",
  # Score/error metric used:
  metric = "RMSE",
  # Cross-validation settings:
  trControl = fit_control,
  # Search grid of tuning parameters
  tuneGrid = tunegrid,
  na.action = na.pass
  )

summary(train)


```

## Predict on test 
```{r}
#using randomForest mtry = 2
#no text features 
test_rf <- test %>%
  mutate(
    log10price_hat = predict(model_rf, test),
    price_hat = 10^log10price_hat - 1
  )

rmsle_lm <- RMSLE(test_rf$price_hat, test$price)
rmsle_lm
MLmetrics::RMSE(test_rf$price_hat, test$price)

#rmsle: 0.357587
#rmse: 450833.4
```



```{r}
#using caret mtry = 2
#no text features 
#test$is_historic = as.factor(test$is_historic)
test_rf_caret <- test %>%
  mutate(
    log10price_hat = predict(model_rf_caret, test),
    price_hat = 10^log10price_hat - 1
  )

rmsle_lm <- RMSLE(test_rf_caret$price_hat, test$price)
rmsle_lm
MLmetrics::RMSE(test_rf_caret$price_hat, test$price)
#rmsle: 0.3878115
#522267.4
```

### Using text features 

```{r}
test_rf_txt <- test %>%
  mutate(
    log10price_hat = predict(model_rf_txt, test),
    price_hat = 10^log10price_hat - 1
  )

rmsle_lm <- RMSLE(test_rf_txt$price_hat, test_rf_txt$price)
rmsle_lm
MLmetrics::RMSE(test_rf_txt$price_hat, test_rf_txt$price)
#0.3674275
#481368
```

```{r}
test_rf_caret_txt <- test %>%
  mutate(
    log10price_hat = predict(model_rf_caret_txt, test),
    price_hat = 10^log10price_hat - 1
  )

rmsle_lm <- RMSLE(test_rf_caret_txt$price_hat, test_rf_txt$price)
rmsle_lm
MLmetrics::RMSE(test_rf_caret_txt$price_hat, test_rf_txt$price)

#rmsle = 0.3982413
#rmse = 540801.3
```

At least for the text vars I select, the text feature models did not perform better







